name: Build Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_macOS:

    runs-on: macos-latest
    
    strategy:
      matrix:
        arch: ['arm', 'x86']

    steps:
    - name: Check out source code
      uses: actions/checkout@v4

    - name: Set up permissions
      run: chmod +x build-macOS_${{ matrix.arch }}.sh 

    - name: Build
      run: ./build-macOS_${{ matrix.arch }}.sh 

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: appdecrypt-macOS-${{ matrix.arch }}
        path: appdecrypt
        
  build_iOS:
    runs-on: macos-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v4

    - name: Set up permissions
      run: chmod +x build-iOS.sh
      
    - name: Install ldid
      run: brew install ldid

    - name: Build
      run: ./build-iOS.sh

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: appdecrypt-iOS
        path: appdecrypt
#  build_macOS_x86:
 #   runs-on: macos-latest
  #  steps:
#
 #     - name: Check out src
  #      uses: actions/checkout@v4
   #   - name: Set up perms
    #    run: chmos +x build-macOS_x86.sh
     # - name: Install ldid
      #  run: brew install ldid
     # - name: Build
      #  run: ./build-macOS_x86.sh
     # - name: Upload artifact
      #  uses: 

